# Site settings
title: Random Notes 
email: 
description: "My little experiments from 'No 42,Milky-way galaxy,Orion arm,Laniakea Supercluster' "
url: "https://jsivark.github.io"
baseurl: "/blog"
twitter_username: _sivark
github_username:  jsivark

avatar: 'assets/minions1.png'
future: true

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge